#define BUILDCACHE_VERSION_MAJOR 0
#define BUILDCACHE_VERSION_MINOR 29
#define BUILDCACHE_VERSION_PATCH 0
#define BUILDCACHE_VERSION_STRING "0.29.0"

#define BUILDCACHE_COPYRIGHT_STRING "Copyright (c) 2018-2024 Marcus Geelnard"

